runtime: go
api_version: go1

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*\.(html|js))$
  static_files: public/\1
  upload: public/.*\.(html|js)$

- url: /.*
  script: _go_app

skip_files:
  - ^node_modules/(?!node\.js$).*
